### ISSUE TITLE
Cannot install requirements.txt

### ISSUE THREAD

**Issue by liuzhanhao** [asuprem/MLEP#5]
We have tried installing the `requirements.txt` in both Ubuntu and MacOS, they both failed for the same error `Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mp/pwh8s_1x71b0vw9q2tsn_2tw0000gn/T/pip-install-bgub0myy/functools32/`

Here are the commands that I run:
```bash
python3 -m venv .env
source .env/bin/activate
pip install -r requirements.txt
```

![image](https://i.imgur.com/PesUexO.png)

**Comment by asuprem** [comment]
You will need python2.7. Many of the learning dependencies require python2.7

**Comment by liuzhanhao** [comment]
We have tried installing it on python 2.7 already. That doesn't work either (screenshot below). Also, the README instructions use python3 (`python3 -m venv .env`), so it would be great if you can state the running environment in the README.

![image](https://i.imgur.com/Uj1hk4a.png)

**Comment by asuprem** [comment]
Hi, so sorry about that! I have fixed parts of the readme to reflect this.

Re. execution - you will need the mrpt module (you can find it here: https://github.com/vioshyvo/mrpt)

You can also install it as:

    pip install git+https://github.com/vioshyvo/mrpt/

If you are on Mac, you may need LLVM.

I'll try to get a shorter requirements list for barebones operations up and running on the repo, and again, sorry for the issues!

**Comment by asuprem** [comment]
Ok, I have added a minrequirements.txt file, which should be easier than dealing will all the stuff in requirements.txt

**Comment by liuzhanhao** [comment]
For the first step, "Create a new Python2.7 virtual environment in directory .env", the README said that we need to run `python -m venv .env`. But it will returns error `No module named venv`. I googled it and found that venv is a new feature in Python3.3: https://docs.python.org/3/library/venv.html

**Comment by ral99** [comment]
Hey, sorry about that! Just updated the readme file with the right command:
`$ virtualenv -p `which python2.7` .env`
